version: 2
enable-beta-ecosystems: true
updates:

  - package-ecosystem: "pub"
    directory: "/super_simple_authentication_server/packages/shared_objects"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pub"
    directory: "/super_simple_authentication_client"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pub"
    directory: "/super_simple_authentication_flutter"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pub"
    directory: "/super_simple_authentication_server"
    schedule:
      interval: "weekly"

