name: shared_objects
description: Shared objects between server and client.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.7.0

dependencies:
  equatable: ^2.0.7
  json_annotation: ^4.9.0

dev_dependencies:
  build_runner: ^2.4.15
  json_serializable: ^6.9.5
  mocktail: ^1.0.4
  test: ^1.25.8
  very_good_analysis: ^7.0.0
