name: super_simple_authentication_client
description: A client for the Super Simple Authentication API
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  http: ^1.4.0
  shared_objects:
    path: ../super_simple_authentication_server/packages/shared_objects

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.25.8
  very_good_analysis: ^6.0.0
