name: super_simple_authentication_server
description: A new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dart_frog: ^1.1.0
  cryptography: ^2.7.0
  meta: ^1.17.0
  postgres_builder: ^2.1.0
  shared_objects:
    path: packages/shared_objects

dev_dependencies:
  mocktail: ^1.0.3
  test: ^1.25.5
  very_good_analysis: ^5.1.0
